### PR TITLE
Homework 2 for student without write permissions

### PR DESCRIPTION
**Pull request by TheVulch**
@amchristi I've finished the second assignment on my own fork, since I still don't have write access to this repo.

### CODE REVIEW

**Comment by TheVulch** [comment]
@amchristi Could something happen about this? I would love me some write permissions.

**Comment by jenkitay** [comment]
You need to send an e-mail to the instructor and TA with your onid to get access.

**Comment by amchristi** [comment]
I added you.

**Comment by TheVulch** [comment]
Merged this with the hw3 fork

**Pull request closed without merging**
